[package]
name = "comm_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.11.0"
serial2 = { version = "0.2.8", optional = true }

[features]
default = ["uart"]
uart = ["dep:serial2"]
